/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeClient: typeof import('./src/components/HomeClient.vue')['default']
    HomeProvider: typeof import('./src/components/HomeProvider.vue')['default']
    Keygen: typeof import('./src/components/Keygen.vue')['default']
    ListarComponentes: typeof import('./src/components/ListarComponentes.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    Plans: typeof import('./src/components/Plans.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
